### ISSUE TITLE
Django 1.8 - Removed in Django 1.9 warning

### ISSUE THREAD

**Issue by Koed00** [ui/django-rq#101]
RemovedInDjango19Warning: 'get_cache' is deprecated in favor of 'caches'.
django_rq/queues.py:56:  ` cache = get_cache(config['USE_REDIS_CACHE'])`

**Comment by epicserve** [comment]
I'm getting this warning as well.

**Comment by selwin** [comment]
Mind issuing a PR for this?

**Comment by epicserve** [comment]
I might be able to work on it tomorrow.

**Comment by epicserve** [comment]
@selwin Any idea when this will get pulled in and made into a release?

**Comment by selwin** [comment]
This is now on PyPI https://pypi.python.org/pypi/django-rq
