### ISSUE TITLE
Next PyPi Release of django-rq

### ISSUE THREAD

**Issue by wastrachan** [ui/django-rq#102]
Do you forsee a new release of django-rq on PyPi in the near future? It would be nice to see a couple of the features that have been added make it into the packaged release.

Are there any pressing issues you'd like to see PRs for to help get there?

**Comment by selwin** [comment]
Just this issue here: https://github.com/ui/django-rq/issues/101 and testing whether thr master branch is stable enough for production use. I haven't had a chance to test it on production after my last few commits. Help on this would be great :)

**Comment by selwin** [comment]
Oh, and I added this new issue :D https://github.com/ui/django-rq/issues/103

**Comment by selwin** [comment]
0.8.0 is now on PyPI

**Comment by daneoshiga** [comment]
Sorry asking in a closed issue, but what Django versions are supported?
I have projects stuck in 1.5 right now.

**Comment by selwin** [comment]
Django 1.4 and up is supported.

**Comment by daneoshiga** [comment]
Thanks :)
