### ISSUE TITLE
Problem running unit tests

### ISSUE THREAD

**Issue by gracaninja** [ui/django-rq#108]
Hello,

I am trying to run a unit test with workers. But somehow the jobs do not get into the queue.

Here is an example:

def f():
    logger.warning("This is a test")
    print "Not doing this..... why"

class WorkerUnitTest(TestCase):

    def test_base(self):
        queue = django_rq.queues.get_queue()
        a = django_rq.enqueue(f)
        logger.info(queue.count)
        logger.info(queue.is_empty())
        w = SimpleWorker([queue], connection=queue.connection)
        w.work(burst=True)

I would expect that after django_rq.enqueue that the count of the queue would be 1. But it is zero and the function is not called when I can the work method.

Any idea on what I am doing wrong?

Thanks

**Comment by selwin** [comment]
Can you show how the queues are configured in `settings.py`? Are you using the `autocommit=False` option?

**Comment by gracaninja** [comment]
Here is my configuration file:

# REDIS
RQ_QUEUES = {
    'default': {
        'URL': os.getenv('REDISCLOUD_URL', 'redis://localhost:6379'),
        'DB': 0,
    },
    'high': {
        'URL': os.getenv('REDISCLOUD_URL', 'redis://localhost:6379'),
        'DB': 0,
    },
    'low': {
        'URL': os.getenv('REDISCLOUD_URL', 'redis://localhost:6379'),
        'DB': 0,
    },
    'maintenance': {
        'URL': os.getenv('REDISCLOUD_URL', 'redis://localhost:6379'),
        'DB': 0,
    },
}

DISABLE_WORKERS = os.getenv('DISABLE_WORKERS', 'False') == "True"

if DISABLE_WORKERS:
    for queueConfig in RQ_QUEUES.itervalues():
        queueConfig['ASYNC'] = False


The queues are working well outside of testing.

**Comment by gracaninja** [comment]
Also when I run the django_rq unit tests I get the following failed tests:

python manage.py test django_rq --settings=django_rq.test_settings --pythonpath=.
Creating test database for alias 'default'...
.............sss.F.F.F......F....
======================================================================
FAIL: test_commit (django_rq.tests.tests.ThreadQueueTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/joaograca/Virtualenvs/unbabel/lib/python2.7/site-packages/django_rq/tests/tests.py", line 477, in test_commit
    self.assertEqual(queue.count, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_enqueue_autocommit_on (django_rq.tests.tests.ThreadQueueTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/joaograca/Virtualenvs/unbabel/lib/python2.7/site-packages/django/test/utils.py", line 224, in inner
    return test_func(*args, **kwargs)
  File "/Users/joaograca/Virtualenvs/unbabel/lib/python2.7/site-packages/django_rq/tests/tests.py", line 444, in test_enqueue_autocommit_on
    self.assertTrue(job.id in queue.job_ids)
AssertionError: False is not true

======================================================================
FAIL: test_success (django_rq.tests.tests.ThreadQueueTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/joaograca/Virtualenvs/unbabel/lib/python2.7/site-packages/django/test/utils.py", line 224, in inner
    return test_func(*args, **kwargs)
  File "/Users/joaograca/Virtualenvs/unbabel/lib/python2.7/site-packages/django_rq/tests/tests.py", line 495, in test_success
    self.assertEqual(queue.count, 1)
AssertionError: 0 != 1

======================================================================
FAIL: test_requeue_job (django_rq.tests.tests.ViewTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/joaograca/Virtualenvs/unbabel/lib/python2.7/site-packages/django_rq/tests/tests.py", line 315, in test_requeue_job
    self.assertTrue(job.is_failed)
AssertionError: False is not true

----------------------------------------------------------------------
Ran 33 tests in 1.188s

FAILED (failures=4, skipped=3)

The current versions of the packages I have are the following:

django-rq==0.8.0
rq==0.5.1

**Comment by gracaninja** [comment]
I found the problem. The redis version I was running on my local machine was below 3.0, this was causing the problem. Tried it on an EC2 machine and it worked with redis 3.0. Update redis on my computer to 3.0 and it also worked.
