### ISSUE TITLE
using with django-redis

### ISSUE THREAD

**Issue by ccurvey** [ui/django-rq#110]
I'm trying to implement connection pooling by combining django-rq with django-redis, and I'm running into a few issues.

The first thing is probably just a documentation update. The existing example says that we should set 

     'CLIENT_CLASS': 'redis_cache.client.DefaultClient',

But the django_redis documentation says that "redis_cache" is deprecated and should be replaced with "django_redis"

But when I do that, I'm getting:
    AttributeError: 'DefaultClient' object has no attribute 'client' 

Which makes sense because there is no "client" property in django_redis.client.DefaultClient. (I've tried 3.7, 3.8 and 4.0 of django_redis)

**Comment by selwin** [comment]
I'm using `django_redis.client.DefaultClient` with on the 3.8 line of `django-redis` in production and it's working fine so it's probably just some installation issues.

I suggest doing a `pip uninstall django-redis` and reinstall with `pip install django-redis` and check if the issue still persists. If it does, open an issue in django-redis' repository.
