### ISSUE TITLE
change the name default

### ISSUE THREAD

**Issue by Sshuichi** [ui/django-rq#111]
Hello , I want to change the default name of the RQ_QUEUES configuration, I don't want to use default because that'll make other apps to share the same workers.

When I change it to something else I have `Could not resolve a Redis connection.` 

I'm new to Redis, how do you create a named connection ?

**Comment by selwin** [comment]
Most probably it's just improper `RQ_QUEUES` configuration. Can you copy paste your configuration here so I can take a look at it?
