### ISSUE TITLE
Managing connections

### ISSUE THREAD

**Issue by hugorodgerbrown** [ui/django-rq#112]
Hi there - this is more of a question than an issue, relating to the number of open connections and how to manage them explicitly (i.e. connection pooling).

Most third party solutions (redistogo, heroku redis) have a restriction on the number of concurrent client connections, and using django-rq on Heroku we're seeing `"ResponseError: max number of clients reached"` errors intermittently (the limit we have is 20). Looking at the database directly using the cli (`> client list`) I can see that the number of clients is hitting the limit very fast - but I have no idea how to control this (if it's even possible).

Is there any kind of connection pooling, and if so how do I control it?

**Comment by hugorodgerbrown** [comment]
Adding some context to this, I am calling this function inside a 'heartbeat' which runs every minute:

```
def check_queue_availability():
    """Test the redis connection, and alert if any failed jobs."""
    try:
        fq = queues.get_failed_queue()
        if fq.count > 0:
            logger.warn(u"There are %i failed jobs - pls check." % fq.count)
    except redis.exceptions.ConnectionError:
        logger.exception(u"Redis queue is currently unavailable: '%s'")
```

The problem appears to be that I get a new client connection to redis on each call of `get_failed_queue`, which then raises the _max number of clients reached_ limit after 20 minutes. Looking at the [rq](http://python-rq.org/docs/connections/) docs, I want to be able to run the check inside a `with Connection` context:

```
with Connection(Redis('localhost', 6379)):
    fq = queues.get_failed_queue()
    ...
```

Should I be dropping down to rq to do this?

**Comment by hugorodgerbrown** [comment]
Further update to this. I can replicate using the django shell:

```python
from django_rq import queues
fq = queues.get_failed_queue()
fq.count
```

If I exit the shell, re-open and run that again, I get another connection. This wouldn't be a problem if the original connection closed as soon as the client process exited, but it has a timeout which appears (anecdotally) to be in the minutes range.

**Comment by Koed00** [comment]
Have you tried lowering the `DEFAULT_TIMEOUT` in the settings? If you set it to under a minute that would give you a little more room.

```
RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': 'some-password',
        'DEFAULT_TIMEOUT': 360,
    }
```
I've struggled with the same thing and unless you pass around the redis connection every time you call your own function, this is the only way to manage it.

**Comment by selwin** [comment]
You can reuse django-redis' connection pools. This is what we do in production. This is documented in the [README](https://github.com/ui/django-rq#support-for-django-redis-and-django-redis-cache)

**Comment by hugorodgerbrown** [comment]
Cheers @selwin - will RTFM next time.
