### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by Koed00** [ui/django-rq#113]
After reading the worker concurrency issue for rq https://github.com/nvie/rq/issues/45 , I wanted to play around with spawning multiple workers from django-rq. 
I've basically just added an option `--count` to the `rqworker` management command, that does the following:

```python
def handle(self, *args, **options):
        worker_count = int(options['count'])
        if worker_count > 1:
            jobs = []
            name = options['name']
            for i in range(worker_count):
                if name:
                    options['name'] = '{}.{}'.format(name, i)
                p = multiprocessing.Process(target=self.worker, args=args, kwargs=options)
                jobs.append(p)
                p.start()
        else:
            self.worker(*args, **options)
```
Full commit is in a branch here b1dc073741504ecdcac41b67284650e253b5fcd7

I've been running it for a few hours now and it seems to be stable and working as expected.
The only problem that comes up is when you do a keyboard interrupt on manage.py. This will be caught by individual workers and they die before the pool has a chance to close them, so the pool raises exceptions. Before I jump any deeper and try to solve that, I would like an opinion on whether this is something that could benefit django-rq.

**Comment by selwin** [comment]
Multiprocessing is something that will be useful. However, I think this feature should be built into RQ instead of this library. If you can build a complete, stable multiprocessing worker, I'll try my best to merge it into RQ :)

**Comment by Koed00** [comment]
I was afraid you were going to say that :) I'll see what I can come up with this weekend.

**Comment by selwin** [comment]
It only makes sense though, right? ;)

**Comment by Koed00** [comment]
It does. Ideally you should only be spawning workhorses.

**Comment by Koed00** [comment]
I diverted from my original goal cause I kept finding things I wanted to do differently. Like package signing and better Django integration. So after the weekend I started designing a native Django multiprocessing task queue [Django-Q](https://github.com/Koed00/django-q). Closing this, but might revisit with new knowledge or ideas.
