### ISSUE TITLE
cannot enable tty mode on non tty input

### ISSUE THREAD

**Issue by sheeshmohsin** [ui/django-rq#116]
Running terminal command with python executes as usual, but running the same python code in django-rq job throws this error `cannot enable tty mode on non tty input` .
Any reasons?

**Comment by selwin** [comment]
Perhaps the terminal command you run expects certain input mode to be available? I'm not sure what would be a good way to fix this. If you find a way to fix this, feel free to open a PR to be considered.

**Comment by sheeshmohsin** [comment]
I am trying to execute this command `sudo docker exec -it emu /home/user/android-sdk-linux/platform-tools/adb devices` . So, here `-t` arg allocate a pseudo-TTY , and `-i` arg is for interactive. So, I just removed both `-it` args, and it started working, its only a workaround. So, I am closing this issue, feel free to reopen this issue.
