### ISSUE TITLE
Inconsistent ordering in admin list view 

### ISSUE THREAD

**Issue by hugorodgerbrown** [ui/django-rq#119]
Minor issue, but the ordering of queues in the admin view is (at least for me) inconsistent. I have 5 queues set up - and if I go to the queues list page (/rq/) in the admin site, and refresh the page they re-order.

<img width="323" alt="screenshot 2015-08-02 09 04 16" src="https://cloud.githubusercontent.com/assets/200944/9025257/9d7568a6-38f5-11e5-80b5-3253dbc3bc9d.png">

becomes

<img width="384" alt="screenshot 2015-08-02 09 04 24" src="https://cloud.githubusercontent.com/assets/200944/9025258/a1a6b916-38f5-11e5-8ad7-f8d4e3c377cb.png">

The bigger issue is that when I click through to the message listing, I don't get the queue that I was expecting, as the listing is based no the queue index. So, if I click on the "default" queue in the first screenshot, I may end up on a page list messages in the email queue instead.

i.e. /rq/queues/1/ isn't referring to a fixed queue.

**Comment by hugorodgerbrown** [comment]
Adding to this. I've followed through [the code](https://github.com/ui/django-rq/blob/master/django_rq/views.py#L24) that presents the queues in the view, and run the following in the shell:

```
>>> [(i,j) for i,j in enumerate(QUEUES)]
[(0, 'email'), (1, 'updates'), (2, 'default'), (3, 'notifications')]
```

Which is consistent (no matter how many times I run it), but **different** from the index values seen on the site itself. On the site, I get the following:

```
/rq/queues/0/ - always 'notifications'
/rq/queues/1/ - either 'email' | 'default'
/rq/queues/2/ - either 'email' | 'default'
/rq/queues/3/ - always 'updates'
/rq/queues/4/ - always 'failed'
```

**Comment by hugorodgerbrown** [comment]
And if I restart the app (it's on Heroku), I now get:

```python
>>> [(i,j) for i,j in enumerate(QUEUES)]
[(0, 'notifications'), (1, 'default'), (2, 'updates'), (3, 'email')]
```

and on the site:

```
/rq/queues/0/ - always 'email'
/rq/queues/1/ - either 'updates' | 'default'
/rq/queues/2/ - always notifications
/rq/queues/3/ - either 'updates' | 'default'
/rq/queues/4/ - always 'failed'
```

**Comment by selwin** [comment]
@hugorodgerbrown does this PR solve your issue? https://github.com/ui/django-rq/pull/118

**Comment by hugorodgerbrown** [comment]
I haven’t tried (would involve pushing to our live environment), but just looking at the diff it looks like it would. Happy to close the related issue.

**Comment by hugorodgerbrown** [comment]
Closing this issue in light of https://github.com/ui/django-rq/pull/118
