### ISSUE TITLE
OperationalError: SSL error: decryption failed or bad record mac

### ISSUE THREAD

**Issue by darkpixel** [ui/django-rq#123]
Not sure if this is a django-rq issue or python-rq, so I figured I'd start here...

My application was working perfectly under Django 1.7.x.

I updated to Django 1.8.x and my workers blew up.

```WARNING 11:29:35 worker 16516 140021590959936 Moving job to u'failed' queue
WARNING 2015-08-30 11:29:35,394 worker 16516 140021590959936 Moving job to u'failed' queue
ERROR 11:29:35 worker 16518 140021590959936 OperationalError: SSL error: decryption failed or bad record mac

Traceback (most recent call last):
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/rq/job.py", line 495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/tank/code/uitintranet/intranet/tasks.py", line 131, in backup_router
    router = Router.objects.get(pk=router_pk)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/db/models/manager.py", line 127, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/db/models/query.py", line 328, in get
    num = len(clone)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/db/models/query.py", line 144, in __len__
    self._fetch_all()
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/db/models/query.py", line 965, in _fetch_all
    self._result_cache = list(self.iterator())
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/db/models/query.py", line 238, in iterator
    results = compiler.execute_sql()
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 840, in execute_sql
    cursor.execute(sql, params)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/home/aaron/.virtualenvs/uitintranet/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
OperationalError: SSL error: decryption failed or bad record mac
```

I checked, and updated rq from 0.5.4 to 0.5.5 and the error continues.
If I run a command from my Django shell_plus without '.delay()', it runs fine.
If I run a command with '.delay()' or I run a command using the scheduler, I get the error above.

I noticed a post on StackOverflow that basically says 'close the DB connection at the beginning of each job'. (http://stackoverflow.com/questions/17523912/django-python-rq-databaseerror-ssl-error-decryption-failed-or-bad-record-mac)

I tested with one of my jobs, and it does fix the problem.  But I'm worried about possible side effects, and having to add a few lines of code to hundreds of job definitions.

**Comment by selwin** [comment]
I've been running django-rq on Django 1.8 for a few weeks with no issuesso I think the error is caused by some custom code in your job. Are you using some kind of concurrency model from within your jib or manually managing DB connections?

**Comment by darkpixel** [comment]
The jobs are all pretty straight forward.  The error I posted above is from a job called ```backup_router(pk)``` which looks at a Router model to get its URL, then uses the requests library to POST login info and get a session cookie, then POSTs again to download a copy of the config.  The config is a long XML string that gets saved back into the database.

Here are the first three lines of the function.  The traceback shows it is failing on the last of these three lines:
```
@job('low')                                                                                                              
def backup_router(router_pk):                                                                                            
    router = Router.objects.get(pk=router_pk)                                                                            
```

I tried updating the psycopg2 library as well and it's still bombing.  I'll keep digging. :)

**Comment by DataGreed** [comment]
See this https://github.com/celery/celery/issues/634

**Comment by darkpixel** [comment]
Hmm.... my postgres database has always been set to *only* allow SSL connections due to the network between the webserver and the DB server being un-trusted.  I verified my cert hasn't expired.  I'll get a change to test more in-depth this weekend.

**Comment by darkpixel** [comment]
After doing a bit more testing, I found that if I do this:
```
def backup_router(router_pk):
  try:
    #my router backup code
  except e:
    pass
```

Everything runs perfectly.

Basically--if any of my jobs throw an error, postgres breaks and the worker becomes useless--accepting jobs and failing on database access forever.

If a worker never throws an error, it will happily continue on working.

**Comment by selwin** [comment]
Does the function run in a postgres transaction? Does it exhibit the same behavior if you run the function with `autocommit` turned on?

**Comment by darkpixel** [comment]
The default in Django 1.8 is ```AUTOCOMMIT = True```.
I tried manually adding it to my settings.py file, restarting the workers and scheduler, and my shell and I still get the same error.

I also tried:
``` RQ = {
     'AUTOCOMMIT': True,
 }
```
in my settings file based on what I saw here: https://github.com/ui/django-rq/blob/8350300ebbd2662528c985472ab78c6d9fd2280b/django_rq/test_settings.py#L133

Same behavior.

**Comment by darkpixel** [comment]
I totally misread celery/celery#634.
It is definitely an SSL issue.
But everything else django-related works fine.

```manage.py runserver```  and ```manage.py shell_plus``` can interact with the DB without problems.

When I specifically force SSL to be disabled in Django (and it's optional in Postgres)
```
      'cwdump': {
          'ENGINE': 'django.db.backends.postgresql_psycopg2',
          'NAME': 'uitintranet',
          'USER': 'uitintranet',
          'PASSWORD': '--redacted--',
          'HOST': '--redacted---',
         'OPTIONS': {
             'sslmode': 'disable',
         },
```
Everything works fine.

When I change 'sslmode' to 'require', Django operates without any problems and the connection is encrypted, but the workers start bombing.

A packet capture shows Postgres throwing a TCP reset and closing the connection.

**Comment by selwin** [comment]
Perhaps the particulars of SSL implementation doesn't allow connection reuse across different processes? To test this hypothesis, could you try running `rqworker` with `SimpleWorker`? `SimpleWorker` doesn't call `os.fork()`.

**Comment by darkpixel** [comment]
Yes, adding ```--worker-class rq.SimpleWorker``` stops the database errors.

**Comment by selwin** [comment]
Yeah, that means it's not actually a Django RQ issue but rather the library itself. You'll probably need to subclass `Worker` and open a new database connection after `os.fork` but before the job is executed. Using a connection pooler may help.

I'm also open to adding additional hooks to `RQ` to make this easier if needed.

**Comment by darkpixel** [comment]
Thanks for the help @selwin.  I guess I don't see any disadvantage to using the SimpleWorker in my setup.  Just good information to know for people using postgres.  I'm going to see if using https://github.com/kennethreitz/django-postgrespool will 'fix' the issue.

**Comment by khamaileon** [comment]
I've got the same problem. Thanks for the solution!

**Comment by crearc** [comment]
Is using SimpleWorker still the optimal solution for this problem? I can't find any better alternatives. And I don't think disabling SSL is a good idea? Running my stuff with SimpleWorker seems to slow my processing speed significantly. Any updates? Did postgrespool work @darkpixel?

**Comment by crearc** [comment]
2.6.2 was just released for pyscopg2 with a close connection fix might resolve it (https://github.com/psycopg/psycopg2/issues/443)? Going to try it out.

**Comment by daneoshiga** [comment]
adding the ` --worker-class rq.SimpleWorker` stopped this particular exception, but now i'm receiving "InterfaceError connection already closed" in some tasks.
