### ISSUE TITLE
AttributeError: 'module' object has no attribute

### ISSUE THREAD

**Issue by lee-kagiso** [ui/django-rq#125]
I am trying to create a background job with RQ:

```python
import django_rq                                                         


    def _send_password_reset_email_async(email):                             
        print(email)                                                         

    # Django admin action to send reset password emails                                                                 
    def send_password_reset_email(modeladmin, request, queryset):            
        for user in queryset:                                                
            django_rq.enqueue(_send_password_reset_email_async, user.email)  
    send_password_reset_email.short_description = 'Send password reset email'
```

I keep getting this error:
```
Traceback (most recent call last):
  File "/home/lee/Code/cas/venv/lib/python3.4/site-packages/rq/worker.py", line 568, in perform_job
    rv = job.perform()
  File "/home/lee/Code/cas/venv/lib/python3.4/site-packages/rq/job.py", line 

495, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "/home/lee/Code/cas/venv/lib/python3.4/site-packages/rq/job.py", line 206, in func
    return import_attribute(self.func_name)
  File "/home/lee/Code/cas/venv/lib/python3.4/site-packages/rq/utils.py", line 151, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute '_send_password_reset_email_async
```

I also posted it to SO earlier http://stackoverflow.com/questions/32733934/rq-attributeerror-module-object-has-no-attribute

**Comment by selwin** [comment]
You need to use "python manage.py rqworker" instead of "rqworker"

**Comment by lee-kagiso** [comment]
I am using `python manage.py rqworker`:

```
python manage.py rqworker
10:14:03 Registering birth of worker lee.19082
10:14:03 RQ worker 'rq:worker:lee.19082' started, version 0.5.5
10:14:03 
10:14:03 *** Listening on default...
10:14:03 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
10:14:25 default: api.actions._send_password_reset_email_async('0264d88327344f7cb55d948f5591ac36@email.com') (30b7a29d-474a-4792-8791-60d51f95af5f)
10:14:25 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
10:14:25 Sent heartbeat to prevent worker timeout. Next one should arrive within 560 seconds.
10:14:25 AttributeError: 'module' object has no attribute '_send_password_reset_email_async'
```

**Comment by lee-kagiso** [comment]
Ping @selwin, sorry but I think you may have closed this issue prematurely?

I am using python 3.4.3 and django 1.7.10.

**Comment by selwin** [comment]
Import problems are usually just about setting your paths correctly. Try doing this from `python manage.py shell`:
```python
from api.actions import _send_password_reset_email_async
```

**Comment by lee-kagiso** [comment]
I get this:
```>>> from api.actions import _send_password_reset_email_async
>>> ```

**Comment by selwin** [comment]
Are you running rqworker from the same directory?

**Comment by lee-kagiso** [comment]
yes

**Comment by selwin** [comment]
Then I'm not sure what the problem is. I'll re-open this issue. Any chance you can provide a failing test case so I can help you debug it?

**Comment by lee-kagiso** [comment]
Sorry, been very busy, going to try and get a failing sample for you.

**Comment by hellpain** [comment]
@lee-kagiso, publish your baggy case as django project on github. Locally we will be able to localize problem in your code or django_rq

**Comment by richardbarran** [comment]
Adding a comment as I too ran into this error:

Rqworker does not dynamically reload when you change your code, but the Django dev webserver does So if you add/modify a task & immediately call it, you may run into this error as the new code (your web code) tries to call the old code (the RQ task).

Stop/restart rqworker and you're ok.

**Comment by Keda87** [comment]
Hi I'm having the same issue with this.

I'm trying to execute some rq tasks in views following below.
```python
        # Send email notification to internal team.
        django_rq.enqueue(
            func=task_email_send_internal_team_for_seller_sign_up,
            args=[
                user.get_full_name(),
                user.email,
                member.telephone,
                company.company_name
            ]
        )

        # Send email notification to internal team.
        django_rq.enqueue(
            func=task_email_sales_for_vendor_approvement,
            args=[member.pk]
        )

        # Send email activation to vendor.
        token = SellerTokenActivation.generate(member=member)
        activation_url = SellerTokenActivation.generate_public_url(token=token.token)
        django_rq.enqueue(
            func=task_email_token_activation_for_vendor,
            args=[
                member.companyinformation.company_name,
                email,
                activation_url,
                username,
                password,
            ]
        )
```

Sometimes the tasks is not executed properly in worker. Some task succeed and the rest failed.
I expect those task are executed properly.

These are my `rq` and `django-rq` versions
```
django-rq==1.2.0
rq==0.12.0
```

Here is the stacktrace from django rq admin
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 793, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 599, in perform
    self._result = self._execute()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 605, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 213, in func
    return import_attribute(self.func_name)
  File "/usr/local/lib/python2.7/dist-packages/rq/utils.py", line 153, in import_attribute
    return getattr(module, attribute)
AttributeError: 'module' object has no attribute 'task_email_token_activation_for_vendor'
```

**Comment by syurchenko** [comment]
@Keda87 I suppose you function "task_email_send_internal_team_for_seller_sign_up" is decorated and decorator does not contain "wraps" decorator.

**Comment by Keda87** [comment]
@syurchenko all my task are not decorated with `@job`. I'm just using regular callable function

**Comment by syurchenko** [comment]
@Keda87, , publish your baggy case as django project on github. Locally we will be able to localize problem

**Comment by guillaumeguy** [comment]
It was an issue with the missing decorator `@job` for me. Thanks !

**Comment by lewiswilliam** [comment]
In my case, it was an issue at the worker end, where one of the ilbraries used was not installed. It kept on pointing at issue at the job function but the issue was something else. If you get into this trouble in future, it is recommended to import the function in the python file from where the worker is being started, in that case the exact error would appear while starting the worker itself.

**Comment by krlx** [comment]
@Keda87 did you find a solution for the issue? Facing the exact same, with a regular callable function - AttributeError: 'module' object has no attribute

**Comment by sergei-iurchenko** [comment]
_send_password_reset_email_async is local function inside function.
Declare it on module level
@krlx
