### ISSUE TITLE
How to run workers in production servers

### ISSUE THREAD

**Issue by mbande** [ui/django-rq#132]
Hi
using ```manage.py``` is not good for use in production.
is there any way to run a worker as daemon?

**Comment by DataGreed** [comment]
Why isn't it good? Pretty much like you run celery with django-celery

**Comment by mbande** [comment]
In a production environment you will want to run the worker in the background as a daemon.
as you mentioned celery, see [this](http://docs.celeryproject.org/en/latest/tutorials/daemonizing.html#daemonizing)
Django's ```manage.py``` is just for development, many people use wsgi in production

**Comment by DataGreed** [comment]
@mbande you do realize, that daemon is just a process with it's output redirected to file rather than stdout? :)))

**Comment by mbodock** [comment]
@mbande i think you're confusig the `runserver` command.
For the workers you can use: Docker¹ (if your application run on containers), Supervisor² or even upstart.

1: https://www.docker.com/
2: http://supervisord.org/

**Comment by DataGreed** [comment]
Supervisor rocks.

**Comment by mbande** [comment]
got it! thank you @mbodock and @DataGreed

**Comment by Proper-Job** [comment]
Supervisor is not Python 3 compatible.

**Comment by rpkilby** [comment]
@Proper-Job - Circus is an alternative that runs on python 3. You could also run both python 2 and python 3. There's nothing preventing supervisord from watching python 3 processes.

**Comment by Proper-Job** [comment]
@rpkilby Thanks!
