### ISSUE TITLE
Problem with simultaneously running workers

### ISSUE THREAD

**Issue by satyrius** [ui/django-rq#136]
I'm running 10 workers simultaneously to offset slow workers (#72). They starts, but after a few minutes only one worker is remaining, all other freezes. Whats wrong?

**Comment by selwin** [comment]
Perhaps this is due to faulty logic in the functions executed by the workers. If you find any indication that this is somehow a bug in django-rq, please reopen this issue.

**Comment by taewookim** [comment]
Having this issue

I have 2 django RQ workers and  RQ scheduler per box (this box has 1gig of memory)... 3 processes by them selves take over 800+ mb of memory

Is there a way to limit their usage?
