### ISSUE TITLE
Version 0.9 isn't installable on Python 3

### ISSUE THREAD

**Issue by aaugustin** [ui/django-rq#141]
Hello,

Version 0.8 was released as a sdist and a Python 2 only wheel. Version 0.9 was only released as a Python 2 only wheel, which makes it impossible to install it on Python 3.

I think the official recommendation is to create a `setup.cfg` file next to `setup.py` containing:

    [bdist_wheel]
    universal = 1

Then if you rerun `python setup.py bdist_wheel upload` that should upload a new wheel compatible with Python 2 and 3 next to the current one.

Thanks!

**Comment by selwin** [comment]
@aaugustin I just did what you mentioned. Let me know if there's still any issue.

**Comment by aaugustin** [comment]
It works, thanks!
