### ISSUE TITLE
Why remove Django 1.4 support?

### ISSUE THREAD

**Issue by vrcmarcos** [ui/django-rq#144]
Hi,

Anyone has a reason for why django 1.4 was deprecated on the 0.9.0 release?

**Comment by ryanisnan** [comment]
Django 1.4 is no longer under LTS (long-term support), so that's probably why.

https://www.djangoproject.com/download/#supported-versions

**Comment by vrcmarcos** [comment]
Neither Django 1.7, but it remains supported. I though that it was for some technical restriction, but have not seen code changes that would be the reason to remove 1.4 support.

I have some 1.4 projects that I want to use this excellent lib. I'll make a pull request to add django 1.4 support.

Thanks for the answer!

**Comment by viaregio** [comment]
Under django 1.4.x you had to write "load url from future" in your templates to get the standard behaviour of the "url" tag from django 1.5 and above. Since django 1.9 you can't do this anymore, you have to remove "load url from future" (pull request #135).

**Comment by selwin** [comment]
Reason is as @viaregio mentioned. It's too much trouble to support Django 1.4
