### ISSUE TITLE
v0.10.0 or v0.9.1

### ISSUE THREAD

**Issue by epicserve** [ui/django-rq#154]
Any chance a version 0.10.0 or 0.9.1 could be made a release on PyPi? I'm currently using `https://github.com/ui/django-rq/archive/356827b.zip` in my requirements. I would prefer to use an actual release.

**Comment by g3rd** [comment]
I second the request, :+1:

**Comment by freeyoung** [comment]
+1. Please make a release in the near future as the current `v0.9.0` is incompatible with django 1.9+.

**Comment by scream4ik** [comment]
+1

**Comment by selwin** [comment]
I'll do it this weekend :)

**Comment by wblock** [comment]
New release, please?  Thank you!

**Comment by selwin** [comment]
Released on PyPI. Sorry for the wait.

**Comment by selwin** [comment]
Actually never mind. I tried uploading the package but PyPI is giving me 400 errors. Looks like it's having some issues. I'll try again soon. 

http://stackoverflow.com/questions/37264536/python-setuptools-upload-failed-400-invalid-uri-uunknown/37265146#37265146

**Comment by swills** [comment]
I see 0.9.1 on PyPi, so something changed. Also, I think PyPi is fixed now, try again?

**Comment by selwin** [comment]
I uploaded it about an hour ago.

**Comment by swills** [comment]
Thanks!
