### ISSUE TITLE
AppResistryNotReady in rqscheduler

### ISSUE THREAD

**Issue by mbodock** [ui/django-rq#155]
Recently, the Django developers choose to revert this issue: [#24007](https://code.djangoproject.com/ticket/24007) which sometimes break my scheduler.

In the [discussion thread ](https://groups.google.com/forum/#!topic/django-developers/YvEzdQU4qUU/discussion) they say something about making a custom worker which loads `django.setup()` before starting the tasks.

Does this error affects anyone else ?

Is it a good ideia run django-rq with a custom Worker?

Traceback

```python
Traceback (most recent call last):
  File "/usr/local/bin/rqscheduler", line 9, in <module>
    load_entry_point('rq-scheduler==0.5.0', 'console_scripts', 'rqscheduler')()
  File "/usr/local/lib/python2.7/dist-packages/rq_scheduler/scripts/rqscheduler.py", line 38, in main
    scheduler.run()
  File "/usr/local/lib/python2.7/dist-packages/rq_scheduler/scheduler.py", line 313, in run
    self.enqueue_jobs()
  File "/usr/local/lib/python2.7/dist-packages/rq_scheduler/scheduler.py", line 295, in enqueue_jobs
    jobs = self.get_jobs_to_queue()
  File "/usr/local/lib/python2.7/dist-packages/rq_scheduler/scheduler.py", line 253, in get_jobs_to_queue
    return self.get_jobs(to_unix(datetime.utcnow()), with_times=with_times)
  File "/usr/local/lib/python2.7/dist-packages/rq_scheduler/scheduler.py", line 236, in get_jobs
    job = Job.fetch(job_id, connection=self.connection)
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 294, in fetch
    job.refresh()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 414, in refresh
    self._result = unpickle(obj.get('result')) if obj.get('result') else None  # noqa
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 53, in unpickle
    raise UnpickleError('Could not unpickle', pickled_string, e)
rq.exceptions.UnpickleError: (u'Could not unpickle', AppRegistryNotReady(AppRegistryNotReady("Models aren't loaded yet.",), <function _load_field at 0x7f517518d410>, ('FooBar', 'Usuario', u'id')))
```

**Comment by mbodock** [comment]
Important [note](https://github.com/django/django/blob/master/docs/releases/1.7.txt#L1006) in the Django docs.

**Comment by selwin** [comment]
I'm not sire why it throws this exception since the rqworker script that ships with this library is a Django management command, not standalone Python script. If you know how to fix it, a PR would be welcome.

**Comment by mbodock** [comment]
I intend to follow the Django instructions. But i'll wait someone with same error.

Perhaps this affects only me, once both my workers and scheduler runs over Docker.
I'm trying alternatives solutions, i'll keep this issue updated.

Ty

**Comment by selwin** [comment]
Just want to be clear, you're using python manage.py rqworker to run the worker, right?

**Comment by mbodock** [comment]
@selwin Yes.

But i wasn't in my `Scheduler`, and this error was in the `Scheduler`.
Now i rebuilt my image to run properly. I'll test for a few more days, and give you guys a feedback.

**Comment by selwin** [comment]
So this error happened in a custom scheduler or worker script and not the management commands that ships with this library, correct?

**Comment by mbodock** [comment]
Yep, was running in the default `Scheduler`. Just yesterday i changed the command to `python manage.py rqscheduler`. Was a honest mistake from my Devops Team.

If it doesn't happens with the Django-rq's rqscheduer, i'll be able to confirm only in the next few days.

It's really hard to fix, since this error is intermittent and i can't reproduce in development.

**Comment by selwin** [comment]
Alright, keep me posted 😀

**Comment by mbodock** [comment]
Since this problem has not happened anymore after i change  `rqscheduler` to `python manage.py rqscheduler`. I'm closing this issue.
If anyone get this error in future fell free to comment.
