### ISSUE TITLE
ImportError: No module named rq.decorators

### ISSUE THREAD

**Issue by SamuelRazzell** [ui/django-rq#157]
I got this error when trying to deploy my app yesterday:

`remote:     django.setup()`
`remote:   File "/app/.heroku/python/lib/python2.7/site-packages/django/__init__.py", line 18, in setup`
`remote:     apps.populate(settings.INSTALLED_APPS)`
`remote:   File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate`
`remote:     app_config = AppConfig.create(entry)`
`remote:   File "/app/.heroku/python/lib/python2.7/site-packages/django/apps/config.py", line 86, in create`
`remote:     module = import_module(entry)`
`remote:   File "/app/.heroku/python/lib/python2.7/importlib/__init__.py", line 37, in import_modul`
`remote:     __import__(name)`
`remote:   File "/app/.heroku/python/lib/python2.7/site-packages/django_rq/__init__.py", line 3, in <module>`
`remote:     from .decorators import job`
`remote:   File "/app/.heroku/python/lib/python2.7/site-packages/django_rq/decorators.py", line 1, in <module>`
`remote:     from rq.decorators import job as _rq_job`
`remote: ImportError: No module named rq.decorators`

I traced it back to the package rq being updated to 1.5 from 0.5.6. I think it broke something with django-rq.

**Comment by mbodock** [comment]
Hi @SamuelRazzell, what happens when you try to run locally ?

Probably rq isn't been installed on Heroku. Did you check your requirements.txt?

**Comment by selwin** [comment]
Looks like `RQ` wasn't properly installed in your environment.
