### ISSUE TITLE
Not clear on using this with Windows

### ISSUE THREAD

**Issue by grwhumphries** [ui/django-rq#164]
Seems that Redis needs to be installed for django-rq to function, however, there isn't a stable release of Redis for Windows (at least none that are obvious).  
Could you include instructions on how to handle this in Windows? Thanks

**Comment by limbera** [comment]
@grwhumphries this app is built ontop of Python RQ which is not compatible with Windows. From their docs:

Limitations
RQ workers will only run on systems that implement fork(). Most notably, this means it is not possible to run the workers on Windows.

**Comment by selwin** [comment]
Closing this issue as RQ is not supported on Windows.

**Comment by mochawich** [comment]
This should help

- Create `simpleworker.py`

```py
from rq import Worker


class BaseDeathPenalty(object):
    def __init__(self, timeout):
        pass

    def __enter__(self):
        pass

    def __exit__(self, type, value, traceback):
        pass


class SimpleWorker(Worker):
    death_penalty_class = BaseDeathPenalty

    def main_work_horse(self, *args, **kwargs):
        raise NotImplementedError("Test worker does not implement this method")

    def execute_job(self, *args, **kwargs):
        """Execute job in same thread/process, do not fork()"""
        return self.perform_job(*args, **kwargs)

```

- Run RQ worker with the following manage command

`rqworker --worker-class simpleworker.SimpleWorker default`


### DISCLAIMER

This solution is to be used only for testing purposes while developing on windows. In no case it should be used for production. It doesn't respect the death penalty when exceeding job maximum timeout for example.

**Comment by selwin** [comment]
Actually, the latest version of RQ also ships with `SimpleWorker` so you can use that for testing purposes: https://github.com/nvie/rq/blob/69b43daa72e0dba554cb4c34b3c01b08a3a7e518/rq/worker.py#L785

**Comment by mochawich** [comment]
Yes it does, there is an issue however. Their `SimpleWorker` inherits `Worker` which uses `UnixSignalDeathPenalty`. You got it right, this class utilizes unix signals that are not available under Windows. Therefore the need for creating this `simpleworker`.

**Comment by ivictbor** [comment]
@mochawich thanks!

**Comment by BrendanSimon** [comment]
It seems the API for `BaseDeathPenalty()` has changed.  I modified it to the following which made it work for me.

```python
class BaseDeathPenalty(object):
    def __init__(self, *args, **kwargs):
        pass

    def __enter__(self, *args, **kwargs):
        pass

    def __exit__(self, *args, **kwargs):
        pass
```
