### ISSUE TITLE
Not able to see Jobs on django-rq/ url (default)

### ISSUE THREAD

**Issue by eddwinpaz** [ui/django-rq#167]
Currently I own a Redis Server and using Django-rq. so far so good the only doubt I've is why is not showing currently Queues on the django url my settings are.

RQ_QUEUES = {
    'default': {
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0,
        'PASSWORD': '',
        'DEFAULT_TIMEOUT': 300,
    }
}

Any Ideas why is always empty? even tough there' are many Currently Queues running up?

I am using the @job decorator on django-rq

**Comment by selwin** [comment]
If your jobs run properly, then everything should be configured properly. By default RQ jobs are deleted after 5 minutes of completion so it's possible that all your jobs have been deleted when you check your dashboard. You can also configure this behaviour using the `result_ttl` argument .
