### ISSUE TITLE
Mulitple failed Queues (if different time-outs)

### ISSUE THREAD

**Issue by depaolim** [ui/django-rq#175]
If I define more than a queue each with different DEFAULT_TIMEOUT than I obtain more than one "failed" queue in the stats view

I think the reason is here:
https://github.com/ui/django-rq/blob/master/django_rq/queues.py#L201

The connection_configs is different because of "DEFAULT_TIMEOUT" item (which is not strictly a connection parameter)

At the moment I used this workaround: specify exactly the same items for each Queue, ... but it is not exactly what I would want

See also #97

**Comment by selwin** [comment]
Are you using the most recent release of DjangoRQ? Could you please provide a screenshot of the problem? As far as I know, this was fixed in https://github.com/ui/django-rq/commit/e5c9b4dbecc3f4fc424e0b4a70aead50e3f07c8d

**Comment by depaolim** [comment]
> Are you using the most recent release of DjangoRQ?
```
# pip freeze | grep django-rq
django-rq==0.9.2
```
> Could you please provide a screenshot of the problem?
![image](https://cloud.githubusercontent.com/assets/443745/17973420/b40d77fa-6ae2-11e6-805f-06d14cecf60e.png)

> As far as I know, this was fixed in e5c9b4d

I think the problem is here
https://github.com/ui/django-rq/blob/master/django_rq/settings.py#L20

because "get_unique_connection_configs"
https://github.com/ui/django-rq/blob/master/django_rq/queues.py#L211

evaluates as different each connection config with different timeout

Maybe there should be a call to "filter_connection_params" as defined in e5c9b4d

**Comment by selwin** [comment]
Yeah, adding `filter_connection_params` to `get_unique_connection_configs` should fix it. PR welcome :)

**Comment by depaolim** [comment]
sorry for the long delay. PR is here :-)
