### ISSUE TITLE
Running multiple workers

### ISSUE THREAD

**Issue by limbera** [ui/django-rq#176]
How can I run multiple instances of django-rq? I know the docs for RQ say "If you want to perform jobs concurrently, simply start more workers", but I am not sure how to achieve this in the real world.

I have a shell script that is being executed by supervisord, the last line of which is
```exec python manage.py rqworker default```

What is the recommended way to run multiple workers?

**Comment by selwin** [comment]
I'm not an expert on supervisord, but I believe the `numprocs` option lets you specify how many instances you want to run: http://supervisord.org/configuration.html

**Comment by taewookim** [comment]
Is there a way to run multiple workers using systemctl?

**Comment by taewookim** [comment]
@selwin Is there an example that shows how to spawn multiple works correctly using systemd?
