### ISSUE TITLE
Mysql timeout after idle periods

### ISSUE THREAD

**Issue by taojoannes** [ui/django-rq#186]
I'm using django-rq to provide a service for shift-based workers to provision servers through ansible.

The queue simply passes the provisioning information to ansible, which runs the operation and passes logging information back to django through url requests in the callback. Each successful job runs for about an hour. When the system is busy we may run up to 20 jobs simultaneously without any problems.

Within the last month, for some reason, we've started seeing MySQL connection has gone away messages in the worker output when the shift first starts.

MariaDB is using the default 8 hour timeout, and I've set CONN_MAX_AGE = 500 
Whenever I start the worker on my development host, and for some time after it runs, I'm seeing a deprecation warning about the urlconf in another package I am using pop up every so often, so I take that to mean that it's restarting the connection according to CONN_MAX_AGE (we don't have the deprecation warnings in production so it's invisible if it's happening)

Looking closely at that behavior, it only seems to appear after a job has passed through the queue, so I think that it is only checking the age of the connection on job completion, and not before a job starts. 

In talking through this, I realize it might be upstream in the django code, but I figure you might be able to zero in on where it's happening faster than I can. 

I'm considering using rq-scheduler to process the queue in burst mode, but I'd rather not have my users wait for a whole minute before their job starts. They startle easily and have my cell phone number. 

Maybe related, in the worker output I get : 
'Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.'

Which is different than the value in django settings.py
RQ_QUEUES['default']['DEFAULT_TIMEOUT'] = 360

**Comment by taojoannes** [comment]
This was unrelated to django-rq. There was a Model.objects.create() inside the function I was queuing that kept that connection open. I closed it explicitly at the beginning of the function and the mysql connection is terminated and recreated as I'd expect.

**Comment by epicserve** [comment]
@taojoannes do you have a code snippet on how you handled this?
