### ISSUE TITLE
Async setting being ignored

### ISSUE THREAD

**Issue by safekidda** [ui/django-rq#189]
django 1.10
djangorestframework 3.4.1
django-rq 0.92

Running on Windows 7, (obviously redis server is not on windows), with the following example I can't get it to run locally on my machine with async=false. Tried various ways by setting on the settings.py and programatically but none work.
# Settings.py

RQ_QUEUES = {
    'default': {
        'ASYNC': False,
        'HOST': 'localhost',
        'PORT': 6379,
        'DB': 0
    }
}
# Views.py

import django_rq

```
queue = django_rq.get_queue(async=False)
queue.enqueue(Tasks.train_model, model.pk)
```

when i inspect the queue _async is False. But it tries to reach the server which doesn't exist and just hangs. Initially tried just setting in the config and then using the @job decorator with delay() which made no difference.

Error 10061 connecting to localhost:6379. No connection could be made because the target machine actively refused it.

Any help is appreciated!

**Comment by selwin** [comment]
`async=False` will try to store enqueued jobs in the Redis server, immediately runs the job and store results in the Redis server. If you want to run this without a server (like when running tests), you should use `FakeRedis`.

**Comment by zyv** [comment]
Too little, too late, but see #106 for a working example.
