### ISSUE TITLE
delay not working if ATOMIC_REQUESTS=True

### ISSUE THREAD

**Issue by guoqiao** [ui/django-rq#193]
Yes today, I added ATOMIC_REQUESTS=True to my database settings, to wrap every request in a transaction in Django. Then today, django-rq stops to process jobs in queue, all jobs remain in `todo` status. It took me about 2 hours to find out the reason is ATOMIC_REQUESTS=True.  

I used a button on page to send ajax request to enqueue jobs to django-rq.
Does any know why django-rq doesn't work while ATOMIC_REQUESTS=True?

**Comment by rpkilby** [comment]
I'm not entirely sure if it discusses the same issue, but this [article](http://www.vinta.com.br/blog/2016/database-concurrency-in-django-the-right-way/) details issues w/ `ATOMIC_REQUESTS` and celery.

**Comment by selwin** [comment]
There's already an issue that aims to improve this library's behavior with Django's db transaction. https://github.com/ui/django-rq/issues/193
