### ISSUE TITLE
 Model class MyModel doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS

### ISSUE THREAD

**Issue by ivictbor** [ui/django-rq#198]
Hi, thanks for your work on this project.
Have some issue here:
I use `django-rq==0.9.2` and `Django==1.9.6`. I have some `job` that uses `MyModel` model:
```
from myapp.models import MyModel

@job
def batch_process(dat):
    MyModel.objects.filter()
```
Sometimes this job works great, but in another times it crashes to failed state with exception
```
 Model class MyModel doesn't declare an explicit app_label and isn't in an application in INSTALLED_APPS
```
And it fails on `from myapp.models import MyModel` line.
In fact I have application that contains `MyModel` in `INSTALLED_APPS` and it has `app_label='myapp'`
Sometimes this fail is random, sometime I have several successes and that fail again. 
According to this http://stackoverflow.com/a/29703136/3479125 possible reason is that I am trying using a model before its application is loaded. But it this I can't understand why it happens during one  `manage.py rqworker` run.

Maybe I am doing something wrong. My question is: can we use imported Model class in directly or we should do it in some other way? Should we force Django to load application or any other thing? 
Thanks

**Comment by selwin** [comment]
This doesn't seem like a Django-RQ issue. It's probably that you haven't setup your models properly.

**Comment by kryptc** [comment]
@ivictbor Were you able to solve your issue?
