### ISSUE TITLE
Irrespective of rqworker queue name argument, always listening on default

### ISSUE THREAD

**Issue by sachinkagarwal** [ui/django-rq#200]
I am trying to create a worker to listen on queue "MYQUEUENAME":

(hootie) sachin@sachin-VirtualBox:~/pycon/hootie/nfsrest$ python manage.py rqworker MYQUEUENAME

But the resulting working always listens on "default"

05:32:48 Registering birth of worker sachin-VirtualBox.19951
05:32:48 RQ worker u'rq:worker:sachin-VirtualBox.19951' started, version 0.6.0
05:32:48 Cleaning registries for queue: default
05:32:48 
05:32:48 *** Listening on default...
05:32:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
^C05:33:15 Got signal SIGINT
05:33:15 Warm shut down requested
05:33:15 Registering death

# Here are the versions of django-rq and rq I am using:

(hootie) sachin@sachin-VirtualBox:~/pycon/hootie/nfsrest$ pip freeze | grep rq
You are using pip version 8.1.2, however version 9.0.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
django-rq==0.9.3
rq==0.6.0
(hootie) sachin@sachin-VirtualBox:~/pycon/hootie/nfsrest$ 

Am I doing something wrong or is this a bug?

**Comment by bigbitbus** [comment]
Just to add here, I downgraded django-rq to 0.8.0 and things work as expected.

**Comment by selwin** [comment]
This should be fixed when https://github.com/ui/django-rq/pull/199 is merged.

**Comment by selwin** [comment]
Fixed in #199
