### ISSUE TITLE
Release 0.9.3 is not a patch release!

### ISSUE THREAD

**Issue by samuelcolvin** [ui/django-rq#203]
Python has a sensible and well document versioning system: Major, Minor, Patch versions. See [PEP 440](https://www.python.org/dev/peps/pep-0440/) for details.

This exists for a reason, please heed it.

0.9.3 is not a patch release, it changes a whole raft of things and effects usage in a numerous ways. 16 files are change with 186+, 26- changes - this is a new minor version at least.

It would also be good if the change log accurately explained the potential consequences of changes, particularly for minor and patch releases.

# What snapped?

You made what presumably felt like a small change which broke our tests in a fairly hard to diagnose way:

adding to `rqworker.py`:
```python
        parser.add_argument('queues', nargs='*', type=str,
                            help='The queues to work on, separated by space')
```

Meant that `call_command('rqworker', 'high', 'default', 'low')` suddenly only actually ran the `default` queue (at least on dj 1.8).

To fix this we needed to change it to `call_command('rqworker', queues=['high', 'default', 'low'])` but this change of usage would not be expected from a patch release and was not clear from the change log.

`</grumble>`

Sorry to sound negative, thanks again for rq and django-rq.

**Comment by selwin** [comment]
This should be fixed in 0.9.4 . Sorry about that.

Will be more careful in incrementing the version number. In my defense, all the feature additions seems quite trivial. If things are stable, I'll bump the version number to 1.0 sometime in the near future.
