### ISSUE TITLE
Could not resolve a Redis connection

### ISSUE THREAD

**Issue by tnedev** [ui/django-rq#205]
Hi, 

I'm trying to enqueue a dependent function, but django_rq raises an exception: Could not resolve a Redis connection

Any thoughts?

`import django_rq
queue = django_rq.get_queue('default')
job = queue.enqueue(func)
queue.enqueue(func2, depends_on=job)   # raises the exception
`

**Comment by selwin** [comment]
This is a bug in version 0.7.0 of RQ. This has been fixed in RQ's master branch but it hasn't been released to PyPI yet. Using RQ's master branch of downgrading to an earlier version of RQ would fix this. This is the PR that fixed the issue: https://github.com/nvie/rq/pull/765

**Comment by tnedev** [comment]
Thanks. Will upgrade.
