### ISSUE TITLE
Heartbeat spams even at --verbosity=0

### ISSUE THREAD

**Issue by jleclanche** [ui/django-rq#209]
The heartbeat() method of rq does `self.log.debug("Sent heartbeat to prevent worker timeout." ...)`.

Despite this going into `debug`, `./manage.py rqworker --verbosity=0` picks up on it. Easy to replicate with `./manage.py rqworker --worker-ttl 1 --verbosity 0`.

**Comment by jastrauss** [comment]
You can change your log level as shown here https://github.com/ui/django-rq#configuring-logging. 

The default log level is "DEBUG". You won't see the heartbeat if the log level is set to something higher than "DEBUG", for example, "INFO".

**Comment by selwin** [comment]
`verbosity` is not an argument the `rqworker` management command recognizes. You can change your logging configuration like @jastrauss suggested.
