### ISSUE TITLE
If the worker loses the DB connection it is not able to reconnect and you must restart it

### ISSUE THREAD

**Issue by depaolim** [ui/django-rq#216]
If the worker loses the DB connection it isn't able to reconnect and you must restart it

Workers should adopt the same DB connection/reconnection policy that Django uses in his request/response cycle

Every time a django-rq worker performs a job, the worker should assure the database-orm-connections are in a valid state.
This policy is enforced by django in its request/response cycle via the function ```close_old_connections```

Look at:
https://github.com/django/django/blob/master/django/db/__init__.py

Similary, in django-rq worker, the ```close_old_connections``` should be called before and after the execution of each job

(see also #49 for some preliminary thoughts)

**Comment by depaolim** [comment]
@selwin please, feel free to tell me your opinion

I set ```DjangoWorker``` as the default django-rq worker.
The rationale behind that decision is that any django-rq worker should be "aware" of the Django ORM connections and manage them according to Django ORM default pattern: reconnect if not valid.
(In a similar way ```DjangoRQ``` is a rq.Queue which is "aware" of Django transactions)

@aaugustin sorry to bother you
you are the author of django persistent-connections (see https://github.com/django/django/commit/2ee21d9f0d9eaed0494f3b9cd4b5bc9beffffae5).
You are perfectly placed to tell me if the approach is correct from the point of view of Django

TIA to both

**Comment by aaugustin** [comment]
Yes I think it would make sense for the RQ worker to handle database connections around tasks like Django does around HTTP requests with:

It boils down to executing:

```
from django.db import connections
for conn in connections.all():
    conn.close_if_unusable_or_obsolete()
```

before and after each task.

See `django/db/__init__.py` for details.

**Comment by depaolim** [comment]
Ok, thank you!

This is the snippet I used in my PR (https://github.com/ui/django-rq/pull/217/files#diff-894c6dcfb79147f4bb0823044b78db19):

```
from django.db import close_old_connections, reset_queries

class DjangoWorker(rq.Worker):
    def perform_job(self, job, queue):
        reset_queries()
        close_old_connections()
        try:
            super(DjangoWorker, self).perform_job(job, queue)
        finally:
            close_old_connections()
```

(I added also a call to ```reset_queries``` as seen in ```django/db/__init__.py```)

**Comment by depaolim** [comment]
The problem is another.
My previous solution is not sufficient.
If ```CONN_MAX_AGE``` is not zero in settings DATABASES, than the worker is unable to reconnect

The picture, as far as I can understand, is the following:

- For each job the rq.Workers starts a "```workhorse```" process via a ```os.fork```
- The ```workhorse``` is in charge of running ```job.perform```
- If here a DB raw disconnection has occurred than the ```django.db.connection``` is invalid. But the ```close_old_connections``` is not aware of the problem. So the ```connection.close()``` is not called
- The ```job.perform``` fails because it can't operate on the DB
- Now the ```db.connection``` is marked as invalid **in the ```workhorse``` process**
- The ```workhorse``` process exits and in the main rq.worker process the db.connection is **still "clean"** (not marked as invalid)

The previous sequence of steps has no solution, the worker must be manually restarted

Please, don't merge the PR #217. I'm working on a more robust one. Any hint is appreciated

**Comment by aaugustin** [comment]
All connections must be closed explicitly prior to forking.

**Comment by depaolim** [comment]
Thank you Aymeric, I will work on that side (... it is not that easy to build a significant test case ...)

**Comment by depaolim** [comment]
Sorry, I'm not able to reproduce the problem. I have built a full integration test https://github.com/depaolim/django-rq/tree/master/integration_test. And everything works fine: rq forks a job and that job connects to database. So, in case of DB failure, only the current job should fail.
There is no need to cleanup any ``connection`` because the next job will operate with a full clean ``db.connections``.
So I'm deleting the PR #217
... unfortunately I have still the problem on my prod box and I don't know why :-(
I can't crash test on that instance at the moment, so I have to wait next days
I close the issue for the moment. Thank you

**Comment by depaolim** [comment]
Ok, found the problem
When ``rqworker`` starts it reads the settings
``settings`` contains INSTALLED_APPS and django initializes every app there cited
In my particular project when a particular app initializes, a DB connection occurs (maybe some initialization occur at the import time and requires a DB connection)
The effect is that the main ``rqworker`` process is connected to the DB
And this situation is dangerous, because the forked job inherits one (or more) connected connection-objects
So, what can we do?
Maybe the situation is somehow dirty: no app should connect at the import time...
But I think we can't make any assumption or fix any constraint on project/apps used inside django-rq
The only viable solution is to close (disconnect) any DB connection just before the ``work`` call
I can make a PR for this
A test case for this behaviour needs be a full integration-test with a full sample project.
A project like this https://github.com/depaolim/django-rq/tree/master/integration_test with a specific test like this https://github.com/depaolim/django-rq/blob/master/integration_test/_tests.py

Do you think a full test case is needed? Or can we assume that a full db-connections-cleanup is a general and safe pattern and django-rq don't need specific test case on that?

... anyway
In rqworker.py I made a simple addition
Before:
```
    use_connection(w.connection)
    w.work(burst=options.get('burst', False))
```
After:
```
    use_connection(w.connection)
    for c in connections.all():
        c.close()
    w.work(burst=options.get('burst', False))
```
and everything is working fine now ;-)

**Comment by aaugustin** [comment]
> no app should connect at the import time...

Indeed, from the point of view of Django's initialization, making SQL queries during setup is unsupported and discouraged. I don't think django-rq should make changes to work around such bugs.

**Comment by depaolim** [comment]
@aaugustin you've got a point

> making SQL queries during setup is unsupported and discouraged

have you any doc/help about this?

If the PR will not be merged I can leave a hint for a workaround suitable for particular (broken) projects:
Create somewhere the following class:
```
from django.db import connections
import rq

class CleanupWorker(rq.Worker):
    def work(self, *args, **kwargs):
        for conn in connections.all():
            conn.close()
        super(TransactionWorker, self).work(*args, **kwargs)
```

And then start the ``rqworker`` with a ``worker-class`` option:
``manage.py rqworker --worker-class somewhere.CleanupWorker``

**Comment by aaugustin** [comment]
See the warning here: https://docs.djangoproject.com/en/1.10/ref/applications/#django.apps.AppConfig.ready

**Comment by jezdez** [comment]
@depaolim If it helps, that's what Celery does to handle database connection during startup and task processing: https://github.com/celery/celery/blob/4d63867c8281e94c74dcdf84fe2a441eaed6671b/celery/fixups/django.py#L135-L192
It more or less closes the connections pre-run-task as well, but does one thing in addition: closing the connection when the worker itself starts, https://github.com/celery/celery/issues/2996

**Comment by ArtyomIvlev** [comment]
Hi, how to reconnect current connection, not all connections?
