### ISSUE TITLE
Paging through Registry jobs does not work correctly

### ISSUE THREAD

**Issue by smaccona** [ui/django-rq#223]
In the Django RQ views, when there are multiple pages of jobs in any of the RQ registries (finished jobs, started jobs, deferred jobs), paging through these jobs in the UI does not work correctly.

This is easily reproducible in any system where there is moderately high job throughput (say a few hundred jobs in the `FinishedJobRegistry` at any given point in time) by examining the finished jobs view for a queue. The first page displays fine, but subsequent pages display only one job (for page 2) or none at all (for all subsequent pages), though the number of pages is listed correctly. Here are pages 2 and 3 for the finished jobs in my `default` queue on one of our production systems right now:

![image](https://cloud.githubusercontent.com/assets/394952/23718198/93fe596e-0404-11e7-944c-8669ebe31014.png)

![image](https://cloud.githubusercontent.com/assets/394952/23718246/b80bfa28-0404-11e7-84b7-a3842eba620a.png)

This is happening because the function signatures in RQ for `Queue.get_job_ids` / `Queue.get_jobs` and `BaseRegistry.get_job_ids` are different. Below are the relevant signatures from RQ.

https://github.com/nvie/rq/blob/master/rq/queue.py#L121: 
```python
def get_job_ids(self, offset=0, length=-1):
```

https://github.com/nvie/rq/blob/master/rq/queue.py#L131:
```python
def get_jobs(self, offset=0, length=-1):
```

https://github.com/nvie/rq/blob/master/rq/registry.py#L57
```
def get_job_ids(self, start=0, end=-1):
```

So `Queue.get_jobs` and `Queue.get_job_ids` expect an offset and a length when requesting jobs, and `BaseRegistry.get_job_ids` expects a start point (same thing as offset) and an end point (not at all the same as a length), but Django RQ uses a length when calling both - e.g. here's the line which gets the jobs for a particular page on the `FinishedJobsRegistry` for a queue:

https://github.com/ui/django-rq/blob/master/django_rq/views.py#L107
```python
job_ids = registry.get_job_ids(offset, items_per_page)
```

The obvious way to fix this is to change the calls in Django RQ to correctly match the signature for RQ's `BaseRegistry.get_job_ids`. There is an argument to be made that RQ's `BaseRegistry.get_job_ids` signature should be changed to be consistent with `Queue.get_job_ids`, but that could be a breaking change for other downstream apps or libraries that are depending on the current signature. @selwin, if you agree with changing this in Django RQ, I will make a PR.

**Comment by selwin** [comment]
Yes, please open a PR so that paging works correctly in Django-RQ. This looks like an annoying bug.

**Comment by smaccona** [comment]
Thanks @selwin. PR submitted.

**Comment by smaccona** [comment]
@selwin - think this is worth a PyPI release?

**Comment by selwin** [comment]
@smaccona version 0.9.5 is now on PyPI. Thanks!
