### ISSUE TITLE
Stopping `rqworker` as a service, mid-task

### ISSUE THREAD

**Issue by iamsteadman** [ui/django-rq#238]
I've been using django-rq for a good while now and love it. As one of my projects scales, the big fear I have is that my CI script - which stops and restarts workers as new code is deployed - will force jobs that are mid-way through running, to cancel.

Presumably in Linux, sending a `stop` using something like Upstart will send a SIGKILL to the worker process. Is this like hitting Ctrl+X or Ctrl+C, whereby usually an iterative job finishes before it recognises the cancellation?

Sorry for such a noob question. I'm just wondering what the best way would be, to ensure a job has finished before the process executing it is killed.

I know that the process is supposed to be able to pick up on new code changes, but I find that it doesn't quite work as I need it to, as sometimes environment variables change and those changes aren't picked up when the worker reloads in-process (if I'm getting the terminology wrong, I apologise). Hence why I really need to stop and start the process, to make sure new environment variables are picked up.

Thanks!

**Comment by selwin** [comment]
Yes, Upstart's `stop` command is equivalent to hitting Ctrl + C when you're running the worker via CLI.

As for environment variable changes not getting picked up when `reload` is sent via Upstart, I do notice that as well and I work around it by sending `stop` and `start` instead of `reload`. If you know of a way to fix this, please let me know.

I'm closing this issue as this is not a real issue, but feel free to reply, I'm always open to suggestions :)

**Comment by iamsteadman** [comment]
Thanks @selwin, I appreciate that. So presumably then, if I did send a `stop`, any tasks currently running would stop immediately? If so, can you think of a way to have a service stopped only when it's finished the current task?

And about the restart thing, now I tend to stop and start the workers in my Ansible script, so stopping the services before new code is deployed, then installing any new requirements and finally starting them again (akin to working with a load balancer).

**Comment by selwin** [comment]
When you send an Upstart `stop` command to a worker, it will give the job 10 seconds to finish. If it doesn't, it will kill the job immediately.

**Comment by iamsteadman** [comment]
Ah OK, thanks for the heads up. I have some quite long-running jobs so I might need to think about the best way to handle this.
