### ISSUE TITLE
Using AUTOCOMMIT=False breaks enqueuing jobs from management commands

### ISSUE THREAD

**Issue by honi** [ui/django-rq#239]
I'm currently doing this as a work around: I run my workers / management commands with a `WORKER` env var defined, and so in settings.py:
```
RQ = {
    'AUTOCOMMIT': True if bool(environ.get('WORKER')) else False,
}
```

**Comment by selwin** [comment]
You can also use `django_rq.get_queue(autocommit=True)`.

**Comment by honi** [comment]
Cool, thanks!
