### ISSUE TITLE
Sending exceptions to Sentry

### ISSUE THREAD

**Issue by efi-mk** [ui/django-rq#252]
Hello,

First of all thank you very much for the wonderful library. 

How do connect django-RQ to sentry. Nothing seems to work. I've configured sentry + logger under my django app. Everything works flawlessly when outside of RQ context, configured according to  sentry's documentation, but the moment I move to jobs executed in RQ nothing works. 
I was naive and looked at the code of rq , hoping that just setting SENTRY_DSN in settings.py will work, I guess not.

Used https://docs.sentry.io/clients/python/integrations/django/ for configuration

What am I missing, what should I do ?

**Comment by efi-mk** [comment]
Created a pull request to fix the exception handling, see https://github.com/ui/django-rq/pull/253

but still loggin does not work.

**Comment by starenka** [comment]
It always worked for me when using `sync` transport like this:

```RAVEN_CONFIG = {
    'dsn': 'sync+https://xxxx@xxxx.cz/',
    'auto_log_stacks': True,
}
```

**Comment by selwin** [comment]
Fixed in https://github.com/ui/django-rq/pull/253
