### ISSUE TITLE
How do I prevent concurrent multiple jobs with the same parameters

### ISSUE THREAD

**Issue by VidJa** [ui/django-rq#258]
How do I prevent multiple jobs in the queue with the same parameters. I am getting issues with jobs trying to write to the same file or the same db record at the same time if I run multiple workers.

**Comment by megapctr** [comment]
I've been researching the same thing. I figured out this is not an important condition in my case. I didn't use this in the end but it may help you out. Please report back if it works 😃 

You could iterate over `queue.jobs` and compare: `job.func is func and job.args == args and job.kwargs == kwargs`. If there's a match, don't enqueue this job.

**Comment by selwin** [comment]
Job deduplication should be implemented in RQ. Proposals are welcome there :)
