### ISSUE TITLE
Option to run multiple workers from the rqworker management command

### ISSUE THREAD

**Issue by as3445** [ui/django-rq#268]
It would be useful if the rqworker management command allowed me to specify if I wanted to run multiple workers at the same time.

**Comment by iamwithnail** [comment]
Oh, goodness. +1000.  
Something like the gunicorn command would be great, so a format something like:

`python manage.py rqworker -w 10`

**Comment by selwin** [comment]
This needs to be built into RQ itself before we can do this in Django-RQ :).

**Comment by taewookim** [comment]
Was there a solution to this other than running a separate process?
