### ISSUE TITLE
Overriding exception handlers

### ISSUE THREAD

**Issue by diminator** [ui/django-rq#74]
This doesn't seems to be supported?
The workers are instantiated upon command without any possibility to push_exc_handler(my_handler)

**Comment by songcy6202** [comment]
Hi, I read this issue , django-rq can't override exception handlers currently. So how to get jobs exception message including a traceback string like normal python function error? I didn't find it in logs or somewhere, could u help me?

**Comment by selwin** [comment]
Fixed in https://github.com/ui/django-rq/pull/134
