### ISSUE TITLE
Formal/confirmed Django 1.7 support?

### ISSUE THREAD

**Issue by stevejalim** [ui/django-rq#82]
Hi there

Has there been any work done yet to ensure tests are still passing on Django 1.7? From the look of Travis (https://travis-ci.org/ui/django-rq) 1.6.1 is the latest build to be tested. 

(I appreciate that may also mean renaming test file names to suit DiscoverRunner)

Cheers
Steve

**Comment by selwin** [comment]
Fixed in https://github.com/ui/django-rq/pull/104
