### ISSUE TITLE
Exceptions in RQ worker processes not being grouped in Sentry

### ISSUE THREAD

**Issue by ryanisnan** [ui/django-rq#86]
I recently migrated form celery/iron-mq to RQ and am now seeing an odd reporting behaviour in sentry.

Errors that have historically been grouped are now being displayed as individual entries within sentry. Has anyone seen this behaviour before?

Logging conf: 

    LOGGING = {
        'version': 1,
        'disable_existing_loggers': False,
        'formatters': {
            'rq_console': {
                'format': '%(asctime)s %(message)s',
                'datefmt': '%H:%M:%S',
            },
        },
        'handlers': {
            'console': {
                'level': 'ERROR',
                'class': 'logging.StreamHandler'
            },
            'rq_console': {
                'level': 'ERROR',
                'class': 'rq.utils.ColorizingStreamHandler',
                'formatter': 'rq_console',
                'exclude': ['%(asctime)s'],
            },
            # If you use sentry for logging
            'sentry': {
                'level': 'ERROR',
                'class': 'raven.contrib.django.handlers.SentryHandler',
            },
        },
        'loggers': {
            'django.request': {
                'handlers': ['console'],
                'level': 'ERROR',
                'propagate': True,
            },
            'rq.worker': {
                'handlers': ['rq_console', 'sentry'],
                'level': 'ERROR'
            },
        }
    }

**Comment by selwin** [comment]
Closing this issue due to lack of response
