### ISSUE TITLE
Redis vs StrictRedis in `get_redis_connection`

### ISSUE THREAD

**Issue by ta2-1** [ui/django-rq#94]
I use rq==0.5.0, redis==2.10.3. 
`USE_REDIS_CACHE` option is used for RQ connections.

If I add a new job with dependency and `depends_on` job hasn't finished yet then RQ tries to add the new job to a deferred set. It uses `Redis` connection where `zadd` parameters are reversed and I get this error:
```
redis.exceptions.ResponseError: value is not a valid float
```
These errors are gone if `Redis` is replaced with `StrictRedis` here 
(https://github.com/ui/django-rq/blob/master/django_rq/queues.py#L79-L81).

Will this change lead to regression or any bugs? 
Can it be applied?

**Comment by ta2-1** [comment]
Hmm, I haven't seen this PR https://github.com/ui/django-rq/pull/92.

**Comment by selwin** [comment]
Strange, differences between `Redis` and `StrictRedis` should be taken care of by `resolve_connection` which gets called when `Queue` object is instantiated [here](https://github.com/nvie/rq/blob/master/rq/queue.py#L37).

Can you provide a failing test case to illustrate the problem?

**Comment by ta2-1** [comment]
@selwin there was a mistake in my first comment. These errors were gone after I switched from `django-redis-cache` to `django-redis`. And connection type (in django_rq/queues.py) doesn't change anything.

**Comment by ta2-1** [comment]
@selwin [here](https://drive.google.com/open?id=0B1Fo4jfTot2tUkdlQWNxODA1ZEk&authuser=1) you can find a test project. After runnig `./manage.py test` you will get the error.

**Comment by ta2-1** [comment]
Close this issue because this is not a bug in django-rq. 
See https://github.com/nvie/rq/issues/498.
