### ISSUE TITLE
Nothing seems to schedule. Been plugging at this for hours.

### ISSUE THREAD

**Issue by chavenor** [ui/django-rq#95]
#### Facts
- I have the scheduler running. 
- I have workers grabbing jobs.
- Non-scheduler jobs are running properly.
- I know the scheduler is working because jobs are instanly being passed into the workers regardless of the date.
- I'm using this in conjunction with django_rq.
- django_rq = 0.7.0 
- Redis = 0.5.0
-  Scheduler = 0.5.0

#### Job to Schedule
```
def run_robot(addresschange_id):
	try:
		addresschange_id = int(addresschange_id)
		addresschange = AddressChange.objects.get(pk=addresschange_id)
		if not addresschange.status_robot == "COMPLETE" or not addresschange.status_robot == "RUNNING":
			addresschange.status_robot="READY"
			addresschange.save()
			print "AddressChange " + str(addresschange_id) + " status_robot='READY' " + str(datetime.utcnow())
			return True
		else:
			return False
	except Exception,e :
		print e
		print "FAILED to set AddressChange ID" + str(addresschange_id) + " status_robot='READY' " + str(datetime.utcnow())
		return False
```
#### Problems

```scheduler.enqueue_at( datetime.now() , func='facts.get.run_robot', args=5 )```
- Dosn't run the job. 
- Throws this error.
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python27\lib\site-packages\rq_scheduler\scheduler.py", line 107, in enqueue_at
    job = self._create_job(func, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\rq_scheduler\scheduler.py", line 75, in _create_job
    if func.__module__ == '__main__':
AttributeError: 'str' object has no attribute '__module__'
```

```scheduler.enqueue_at( datetime.now()+timedelta(minutes=10) , func=run_robot(5) )```
- Job is ran instantly.
- Throws this error.
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Python27\lib\site-packages\rq_scheduler\scheduler.py", line 107, in enqueue_at
    job = self._create_job(func, args=args, kwargs=kwargs)
  File "C:\Python27\lib\site-packages\rq_scheduler\scheduler.py", line 75, in _create_job
    if func.__module__ == '__main__':
AttributeError: 'NoneType' object has no attribute '__module__'
```

```scheduler.enqueue_in(timedelta(seconds=30), run_robot, 5)```
- Job is queued. 
- Job is never ran.

```job_instances = scheduler.get_jobs()```
- Gives me
``` [Job(u'9b8bfe13-509d-44de-9253-bcd1dc397869', enqueued_at=None), Job(u'6e4a7544-e61c-46a9-8115-5fd1272c4a36', enqueued_at=None)] ```

I've been spending hours trying all kinds of combinations but nothing seems to work as expected.   

What am I doing wrong?  I'm out of ideas but really want to use this to schedule a jobs for my Linux workers.

Thanks!

**Comment by selwin** [comment]
Hi there, for this to work, you'll need `rq-scheduler` 0.5.1:
`scheduler.enqueue_at( datetime.now() , func='facts.get.run_robot', args=5 )`

The syntax for this one is wrong:
`scheduler.enqueue_at( datetime.now()+timedelta(minutes=10) , func=run_robot(5) )`

It should be:
`scheduler.enqueue_at( datetime.now()+timedelta(minutes=10) , func=run_robot, args=[5] )`

**Comment by chavenor** [comment]
Updated scheduler to 0.5.1

Tried.
```scheduler.enqueue_at( datetime.now()+timedelta(minutes=10) , func=run_robot, args=[5]```

Throws Error. 
```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 543, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 490, in perform
    self._result = self.func(*self.args, **self.kwargs)
TypeError: run_robot() got an unexpected keyword argument 'args'```

**Comment by chavenor** [comment]
Does the ```rqscheduler``` actually execute the job?

**Comment by chavenor** [comment]
Updated to 0.5.1. 

Trying to run. 
```scheduler.enqueue_at(datetime.now(), func='facts.get.run_robot', args=[5] ) ```

It seems to wait ~approx minute before firing which is good.

Throwing this error.
``` 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/rq/worker.py", line 543, in perform_job
    rv = job.perform()
  File "/usr/local/lib/python2.7/dist-packages/rq/job.py", line 490, in perform
    self._result = self.func(*self.args, **self.kwargs)
TypeError: run_robot() got an unexpected keyword argument 'args'
```

**Comment by selwin** [comment]
Can you try to see if this works?
```python
scheduler.enqueue_at(datetime.now(), func='facts.get.run_robot', 5)
```

**Comment by chavenor** [comment]
Yup just finished testing this.

```scheduler.enqueue_at(datetime.utcnow()+timedelta(minutes=10), func='facts.get.run_robot', addresschange_id=5 )```

**Comment by chavenor** [comment]
It worked.

**Comment by chavenor** [comment]
Or at least it seems ten minutes when by and it worked.

**Comment by chavenor** [comment]
I think we're good.

**Comment by chavenor** [comment]
@selwin do you have an amazon wish list or something -- I'd like to toss you something for helping.

**Comment by chavenor** [comment]
Also if I use a ```datetime``` object way in the past will it work?

**Comment by selwin** [comment]
@chavenor no I don't, don't worry about it ;).

Yes, you could use a date in the past and it will get scheduled the next time `rq-scheduler` runs.

**Comment by chavenor** [comment]
@selwin  you the man.  If you get into a jam let me know I as I owe you one. :) 

Thanks again!

**Comment by propero** [comment]
@selwin  thanks for great replays. My question: is it possible that rqscheduler fires after 1 minute, despite interval is set to second.

this is the code:
```
scheduler=get_scheduler('default',interval=1)

def start():
  job=scheduler.enqueue_at(datetime.utcnow(),'CasparRunner.casparCommunicator.commands.testSchedule')
    print(scheduler.get_jobs())
    # queue.enqueue('CasparRunner.casparCommunicator.commands.testSchedule')
    return {'view':"CasparRunner/index.html"}

@job
def testSchedule():
    print("Was in testSchedule")
    comm.sendCommand("play 1 amb")
    pass
```

this just waits for a minute and than starts executing. Strange part is that it always executes at same second of the minute. Is this expected?
