### ISSUE TITLE
Workers Seem to Timeout but still sending heartbeat?

### ISSUE THREAD

**Issue by changeaddress** [ui/django-rq#96]
I noticed last night that a lot of my workers vanished from my dashboard.   Yet the workers still were sending heartbeats out?   Any idea why or any idea to restart a worker when it loses it's connection?

![workers-not-there](https://cloud.githubusercontent.com/assets/8561798/6388200/bd305936-bd5c-11e4-83cf-c79e641b5cf1.png)

Thanks!

**Comment by changeaddress** [comment]
BUMP else experiencing this?

**Comment by selwin** [comment]
You should use process managers such as supervisor or upstart to manage your workers. http://python-rq.org/patterns/supervisor/ has an example supervisor configuration
