### ISSUE TITLE
Mulitple failed Queues

### ISSUE THREAD

**Issue by mbodock** [ui/django-rq#97]
After adding a second queue `low`, my django_rq now displays two `failed` Queues as the img below:
![issue image](https://lh6.googleusercontent.com/-FnFlIj5am5k/VQBHNS5MI7I/AAAAAAAAM_M/klqXz3jsrpE/s1318/djagnorq.png)

**Comment by mbodock** [comment]
Can't reproduce in newer versions.

Probably fixed in a future version.

**Comment by eriktelepovsky** [comment]
Same issue here. Failed queue is displayed twice in Django admin. 

Django==1.9
django-rq==0.9.3
rq==0.6.0
