### ISSUE TITLE
`rqscheduler -i` works, but `manage.py rqscheduler -i` doesn't.

### ISSUE THREAD

**Issue by jorgecarleitao** [ui/django-rq#98]
`--interval=` works in both cases, but for consistency, it may be useful to add all options of rqscheduler also here.

pip freeze:

```
Django==1.7.6
click==3.3
django-rq==0.7.0
redis==2.10.3
rq==0.5.1
rq-scheduler==0.5.1
```

**Comment by selwin** [comment]
Agreed, PR welcome :)
